# Generated by Django 4.2 on 2023-04-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_materiais', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materiais',
            new_name='Material',
        ),
    ]
