# Generated by Django 4.2 on 2023-04-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_materiais', '0002_rename_materiais_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='tipo',
            new_name='tipo_material',
        ),
    ]
