<MDFillRoundFlatButtonCustom@MDFlatButton+HoverBehavior>

<TelaPrincipal>

    MDBottomNavigation:
        panel_color: 0.1, 0.3, 0.2, 0.8
        selected_color_background: "orange"
        text_color_active: "black"
        text_color_normal: "white"

        MDBottomNavigationItem:
            name: 'inicio'
            text: 'INICIO'
            icon: 'home'
            badge_icon: ""
            
            MDGridLayout:
                cols: 1

                MDRectangleFlatIconButton:
                    id: conexao_icon
                    name: 'conexao_icon'
                    font_name: app.font_monofonto
                    text: "CONECTANDO"
                    line_color: 0, 0, 0, 0
                    text_color: 1, 1, 0, 1
                    icon_color: 1, 1, 0, 1
                    icon: 'database'
                    pos_hint: {'center_x': 0.5}
                    on_release:
                        root.tryConnect()


            MDFillRoundFlatButtonCustom:
                text: "LOGOUT"
                font_name: app.font_monofonto
                md_bg_color: .1, .1, .1, 1
                size_hint_y: None
                size_hint_x: None
                height: 50
                width: 200
                pos_hint: {"center_x": .5, "center_y": .5}
                on_release: 
                    root.logout()
                    root.manager.current = "login_screen"
                    
        MDBottomNavigationItem:
            name: 'cadastrar'
            text: 'CADASTRAR'
            icon: 'account'
            badge_icon: ""

            MDBoxLayout:
                orientation: "vertical"
                spacing: dp(20)
                padding: dp(10)

                MDFillRoundFlatButtonCustom:
                    text: "CADASTRAR NOVO CLIENTE"
                    font_name: app.font_monofonto
                    font_size: "24sp"
                    md_bg_color: .1, .1, .1, 1
                    pos_hint: {"center_x": .5, "center_y": .5}
                    size_hint: (1, 0.0)
                    on_release:
                        root.manager.current = "cadastro_cliente"
                        
                MDBoxLayout:
                    orientation: "vertical"

                    MDFillRoundFlatButtonCustom:
                        text: "CADASTRAR NOVO SERVIÇO"
                        font_name: app.font_monofonto
                        font_size: "24sp"
                        md_bg_color: .1, .1, .1, 1
                        pos_hint: {"center_x": .5, "center_y": .5}
                        size_hint: (1, 0.0)
                        on_release:
                            root.manager.current = "cadastro_service"

                    MDBoxLayout:
                        orientation: "horizontal"

                        MDFillRoundFlatButtonCustom:
                            text: "NOVO SERVIÇO"
                            font_name: app.font_monofonto
                            font_size: "24sp"
                            md_bg_color: .1, .1, .1, 1
                            pos_hint: {"center_x": .5, "center_y": .5}
                            size_hint: (1, 0.0)
                            on_release:
                                root.manager.current = "new_service"


        MDBottomNavigationItem:
            name: 'consultar'
            text: 'CONSULTAR'
            icon: 'search-web'
            badge_icon: ""

            MDLabel:
                text: 'TELA DE CONSULTA'
                halign: 'center'

        MDBottomNavigationItem:
            name: 'alterar'
            text: 'ALTERAR'
            icon: 'pencil'

            MDLabel:
                text: 'TELA DE ALTERAÇÕES'
                halign: 'center'
                
        MDBottomNavigationItem:
            name: 'deletar'
            text: "DELETAR"
            icon: 'delete'
            

            MDLabel:
                text: 'TELA DE EXCLUSÃO'
                halign: 'center'
                