#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include LoginScreen login_screen.LoginScreen
#:include TelaPrincipal tela_principal.TelaPrincipal

<MainScreenManager>
    transition: NoTransition()

    TelaPrincipal:
        id: tela_principal
        name: 'tela_principal'
    
    LoginScreen:
        id: login_screen
        name: 'login_screen'