#:import FadeTransition kivy.uix.screenmanager.FadeTransition 
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include LoginScreen login_screen.LoginScreen
#:include TelaPrincipal tela_principal.TelaPrincipal

<MainScreenManager>
    transition: NoTransition()

    LoginScreen:
        id: login_screen
        name: 'login_screen'

    TelaPrincipal:
        id: tela_principal
        name: 'tela_principal'