#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include LoginScreen login_screen.LoginScreen
#:include TelaPrincipal tela_principal.TelaPrincipal
#:include CadastroCliente cadastroCliente.CadastroCliente
#:include CadastroService cadastroService.CadastroService
#:include NewService newService.NewService
#:include ConsultaCliente consultaCliente.ConsultaCliente
#:include ConsultaService consultaService.ConsultaService
#:include ConsultaUnica consultaUnica.ConsultaUnica

<MainScreenManager>
    transition: NoTransition()
    
    ConsultaUnica:
        id: consulta_unica
        name: 'consulta_unica'

    ConsultaOrcamento:
        id: consulta_orcamento
        name: 'consulta_orcamento'

    ConsultaCliente:
        id: consulta_cliente
        name: 'consulta_cliente'

    TelaPrincipal:
        id: tela_principal
        name: 'tela_principal'

    NewService:
        id: new_service
        name: 'new_service'

    CadastroService:
        id: cadastro_service
        name: 'cadastro_service'

    CadastroCliente:
        id: cadastro_cliente
        name: 'cadastro_cliente'
    
    ConsultaService:
        id: consulta_service
        name: 'consulta_service'
    
    AlterarCliente:
        id: alterar_cliente
        name: 'alterar_cliente'
    
    AlterarService:
        id: alterar_service
        name: 'alterar_service'
    
    AlterarRegistro:
        id: alterar_registro
        name: 'alterar_registro'